version: '3.8'

services:
  db:
    image: mysql:8.1
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
