on:
  push:
    branches:
      - main

env:
  APP_PATH: /home/mpctxkqx/agendachretien-strapi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4.0.2
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: echo "{\"type\":\"module\"}" > build/package.json
      - uses: jossef/action-set-json-field@v2.2
        with:
          file: package.json
          field: type
          value: commonjs
      - uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: 5022
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "build public config database app.js package.json package-lock.json"
          TARGET: $APP_PATH
          SCRIPT_AFTER: |
            /usr/sbin/cloudlinux-selector install-modules --json --interpreter=nodejs --app-root=${{env.APP_PATH}}
            /usr/sbin/cloudlinux-selector restart --json --interpreter=nodejs --app-root=${{env.APP_PATH}}
